apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-hostname-ingress
  
  
spec: 
  ingressClassName: nginx 
  rules: 
  - host: myapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: httpbin-service
            port:
              number: 80